package webskitters.com.stockup.Utils;

/**
 * Created by imran khan on 02-05-2016.
 */
public enum DialogType {
    //profile
    SMOKER, COUNTRY, STATE, REALATIONSHIP, OCCUPATION, RELIGION, SEEKING,HEIGHT,HOBBY, AGE_OF_IDEAL_PARTNER, PHYSICAL_APPEARANCE_SEEKING_FOR_PARTNER, EYE, HAIR_COLOR, APPEARANCE, ETHNICITY, HIGHEST_EDUCATION, LANGUAGE_SPEAK, COUNTRY_ENJOYED_VISITING, INTERESTS, SPORTS_U_ENJOYED, PETS,

    //sign up
    TERMS_AND_CONDITION, PRIVACY_POLICY,

    //Profile
    FORGET_PASSWORD, MEMBERSHIP,

    //AddPhoto
    TRAVEL_PRIVACY,

    LOGOUT,DELETE_ACCOUNT;

}